### ISSUE TITLE
Create Cart Page

### ISSUE THREAD

**Issue by Haider037** [JoseChaconUrias/GroceryStore#23]
- Display all items
- Display total number of items
- Option to remove an item and add more of the same item
- Button to back to shopping page
- Button to the checkout page

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a new Cart component to display all items, total number of items, options to remove or add items, and buttons to navigate back to shopping and to checkout.

You can review changes in this commit: https://github.com/lattaai13/JoseChaconUrias-GroceryStore-23/commit/ffa87949c00d56f9879d24c8f4c99c844077476b.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
